language: generic
before_install:
- openssl aes-256-cbc -K $encrypted_416e7b4ab6f4_key -iv $encrypted_416e7b4ab6f4_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ travisaw@travisawagner.com:/travisaw.com/test/song-lyrics-password-generator
  on:
    branch: master
